export const ICON_NAMES = [
	'Activity',
	'Air',
	'AlertCircle',
	'Ambulance',
	'ArrowLeft',
	'Bone',
	'Brain',
	'BriefcaseMedical',
	'CheckCircle',
	'Circle',
	'CircleDot',
	'ClipboardCheck',
	'ClipboardList',
	'Construction',
	'Droplet',
	'Eye',
	'Footprints',
	'Gauge',
	'Hand',
	'HeartPulse',
	'Hospital',
	'MessageCircle',
	'MessageSquareQuote',
	'MessageSquareText',
	'PhoneCall',
	'Plug',
	'Power',
	'Ruler',
	'Scan',
	'ScanFace',
	'Search',
	'Shield',
	'ShieldAlert',
	'ShieldCheck',
	'StretchHorizontal',
	'Thermometer',
	'Truck',
	'UserPlus',
	'UserRoundSearch',
	'Utensils',
	'Wind',
	'X',
	'Zap'
] as const;

export type IconName = (typeof ICON_NAMES)[number];
